# Generated by Django 6.1.1 on 2026-09-03 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('AWAITING_APPROVAL', 'Awaiting Human Approval'), ('EXECUTED', 'Action Executed'), ('REJECTED', 'Action Rejected'), ('FAILED', 'Failed')], default='RUNNING', max_length=30)),
                ('proposed_action', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_npr', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=27.842)),
                ('longitude', models.FloatField(default=84.521)),
                ('slope_deg', models.FloatField(default=45.0)),
                ('ndvi', models.FloatField(default=0.18)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTraceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('step_type', models.CharField(max_length=20)),
                ('thought', models.TextField(blank=True, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_args', models.JSONField(blank=True, null=True)),
                ('tool_result', models.TextField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='agent_api.agentrun')),
            ],
            options={
                'ordering': ['step_index'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='triggering_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.sensornode'),
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rain_72h', models.FloatField(default=0.0)),
                ('soil_moisture', models.FloatField()),
                ('acoustic_vib', models.FloatField()),
                ('is_critical', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_api.sensornode')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
